### ISSUE TITLE
オーディオファイルへのアクセス

### ISSUE THREAD

**Issue by soichiro0210** [reazon-research/ReazonSpeech#12]
日本語音声コーパスに新たなラベル付けを行いたいと思っております。
こちらのデータセットのオーディオファイルはアクセスできますでしょうか？

Hugging Faceのdatasetsからアクセスした場合、オーディオファイルについてはpathまで取得できたもののオーディオファイルを直接参照するところまでは至りませんでした。
また、コーパス構築ツールキットも使用させていただきましたがtest.m2tsファイルが見当たらず、コーパスを作成することはできませんでした。

**Comment by fujimotos** [comment]
> こちらのデータセットのオーディオファイルはアクセスできますでしょうか？

コーパスの音声ファイルは`datasets`のキャッシュパスから参照可能です。
最初に`datasets.load_dataset`でコーパスデータの読み込みを行った上で、

```console
$ python3
>>> from datasets import load_dataset
>>> ds = load_dataset("reazon-research/reazonspeech", "small")
>>> record = ds["train"][0]
>>> print(record)
{ "name": "000/e7fb3323c280c.flac",  'audio': {'path': '/path/to/000/e7fb3323c280c.flac', ...}, "transcription": "..."}
```

次のように`record["audio"]["path"]`から音声ファイルの参照が可能です。
音声に対応する字幕は`record["transcription"]`に格納されています。

```console
$ file /path/to/000/e7fb3323c280c.flac
FLAC audio bitstream data, 16 bit, mono, 16 kHz, 66454 samples
```

データセットの仕組みの詳細はHugging Face Datasetsのドキュメントを参照ください。

https://huggingface.co/docs/datasets/index
