### ISSUE TITLE
failed to download reazon-research/reazonspeech corpus from Hugging Face 

### ISSUE THREAD

**Issue by zira-wang** [reazon-research/ReazonSpeech#15]
Hi, i have try to download reazon-research/reazonspeech corpus from Hugging Face, but failed.

load script:
`datasets.load_dataset("reazon-research/reazonspeech")`

error massege:
`ConnectionError: Couldn't reach https://reazonspeech.s3.abci.ai/small.tsv (error 403)`

How do i handle this error

**Comment by fujimotos** [comment]
> Hi, i have try to download reazon-research/reazonspeech corpus from Hugging Face, but failed.

@zira-wang Sorry for inconvenience!

Right now, the hosting storage we've been using for ReazonSpeech datasets
is out of service (due to a new fiscal year starting in Japan).

We are under the process of renewing our contract so that we can continue
to use the space for hosting our datasets. The service should open back again
soon(ish).

**Comment by zira-wang** [comment]
@fujimotos Thank you. Looking forward to using it soon.

**Comment by fujimotos** [comment]
@zira-wang The ReazonSpeech dataset is back to online again now.

https://huggingface.co/datasets/reazon-research/reazonspeech

You should be able to check out sample entries on Preview Viewer;
Just let us know if you fail to open the dataset.

**Comment by Charliewei1** [comment]
@fujimotos 
Hello, I am still encountering the same error when attempting to download the dataset:

```python
from datasets import load_dataset

dataset = load_dataset("reazon-research/reazonspeech")
```
```
ConnectionError: Couldn't reach https://reazonspeech.s3.abci.ai/small.tsv (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='reazonspeech.s3.abci.ai', port=443): Max retries exceeded with url: /small.tsv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49489830d0>: Failed to establish a new connection: [Errno 111] Connection refused'))")))
```
The URL may not have been updated.

**Comment by fujimotos** [comment]
> Hello, I am still encountering the same error when attempting to download the dataset:

@Charliewei1 The hosting service is currently under the maintenance.
Here is some more details on the operation schedule:

> * Start: Fri, Jun 09, 2023 13:00
> * End: Mon, Jun 12 17:00
> * Status: ABCI is out of service due to the maintenance of ABCI water cooling system.

The service will be back on next Monday. So wait for that.

**Comment by Charliewei1** [comment]
@fujimotos Thank you for the update. I appreciate your response and will wait for the service to be restored on Monday.
