### ISSUE TITLE
Difficulty Reproducing Reported Results on TEDxJP

### ISSUE THREAD

**Issue by sinhat98** [reazon-research/ReazonSpeech#16]
Hi, thank you for creating an excellent Japanese speech recognition model, reazonspeech-next, which was recently released.

I would like to evaluate the performance of this model on TEDxJP. However, I have been unable to reproduce the evaluation results reported in [this](https://github.com/reazon-research/ReazonSpeech/releases/tag/v1.1.0).

I conducted the experiment as follows.

To preprocess TEDxJP, I used the ESPNet script provided in the following link:
https://github.com/espnet/espnet/blob/master/egs2/laborotv/asr1/local/tedx-jp-10k_data_prep.sh

To ensure consistency between inference and evaluation, I used reazonspeech.transcribe() and reazonspeech.text.cer() to calculate the Character Error Rate (CER).

I calculated CER using two methods in the experiment:

Calculating the CER for each utterance and taking the arithmetic mean of all utterances.
Merging the reference text and predicted text for each utterance and calculating the CER for the entire dataset.
In both cases, the CER was 16% and 11%, respectively, which is lower than the reported accuracy.

I would appreciate it if you could tell me what needs to be improved to reproduce the reported results accurately.

**Comment by fujimotos** [comment]
> To ensure consistency between inference and evaluation, I used
> reazonspeech.transcribe() and reazonspeech.text.cer() to calculate the
> Character Error Rate (CER).

@sinhat98 In addition to `reazonspeech.text`, we also normalize
numeric expressions when computing CER. Here is Python code
(requires [num2words](https://github.com/savoirfairelinux/num2words) library):

```python3
import re
import num2words

text = "4月15日"
conv = lambda m: num2words.num2words(m.group(0), lang='ja')
text = re.sub(r'\d+\.?\d*', conv, text)  # "四月十五日"
```

This logic is in accordance with what the previous researches did (for
example, see [JTubeSpeech](https://github.com/sarulab-speech/Jtubespeech/blob/master/scripts/align.py#L80-L81)), and I think this is likely the reason why
you got a different result.

> Calculating the CER for each utterance and taking the arithmetic mean of all utterances.
> Merging the reference text and predicted text for each utterance and calculating the CER for the entire dataset.

I think the standard way to compute CER is neither of the two methods,
but $\frac{\sum{\textit{edit distance}}}{\sum{\textit{len(ground truth)}}}$.


See [how Kaldi computes WER](https://github.com/kaldi-asr/kaldi/blob/master/src/bin/compute-wer.cc#L104-L107) for reference.

**Comment by fujimotos** [comment]
> To ensure consistency between inference and evaluation, I used
> reazonspeech.transcribe() and reazonspeech.text.cer() to calculate the
> Character Error Rate (CER).

@sinhat98 In addition to `reazonspeech.text.normalize`, we also
normalize numeric expressions when computing CER. Here is
Python code (requires [num2words](https://github.com/savoirfairelinux/num2words) library):

```python3
import re
import num2words

text = "4月15日"
conv = lambda m: num2words.num2words(m.group(0), lang='ja')
text = re.sub(r'\d+\.?\d*', conv, text)  # "四月十五日"
```

This logic is in accordance with what the previous researches did (for
example, see [JTubeSpeech](https://github.com/sarulab-speech/Jtubespeech/blob/master/scripts/align.py#L80-L81)), and I think this is likely the reason why
you got a different result.

> Calculating the CER for each utterance and taking the arithmetic mean of all utterances.
> Merging the reference text and predicted text for each utterance and calculating the CER for the entire dataset.

I think the standard way to compute CER is neither of the two methods,
but $\frac{\sum{\textit{edit distance}}}{\sum{\textit{len(ground truth)}}}$.


See [how Kaldi computes WER](https://github.com/kaldi-asr/kaldi/blob/master/src/bin/compute-wer.cc#L104-L107) for reference.

**Comment by fujimotos** [comment]
> To ensure consistency between inference and evaluation, I used
> reazonspeech.transcribe() and reazonspeech.text.cer() to calculate the
> Character Error Rate (CER).

@sinhat98 In addition to `reazonspeech.text.normalize`, we also
normalize numeric expressions when computing CER for benchmark
datasets. Here is Python code (requires [num2words](https://github.com/savoirfairelinux/num2words) library):

```python3
import re
import num2words

text = "4月15日"
conv = lambda m: num2words.num2words(m.group(0), lang='ja')
text = re.sub(r'\d+\.?\d*', conv, text)  # "四月十五日"
```

This logic is in accordance with what the previous researches did (for
example, see [JTubeSpeech](https://github.com/sarulab-speech/Jtubespeech/blob/master/scripts/align.py#L80-L81)), and I think this is likely the reason why
you got a different result.

> Calculating the CER for each utterance and taking the arithmetic mean of all utterances.
> Merging the reference text and predicted text for each utterance and calculating the CER for the entire dataset.

I think the standard way to compute CER for an entire dataset is  $\frac{\sum{\textit{edit distance}}}{\sum{\textit{len(ground truth)}}}$.
See [how Kaldi computes WER](https://github.com/kaldi-asr/kaldi/blob/master/src/bin/compute-wer.cc#L104-L107) for reference.

**Comment by fujimotos** [comment]
> To ensure consistency between inference and evaluation, I used
> reazonspeech.transcribe() and reazonspeech.text.cer() to calculate the
> Character Error Rate (CER).

@sinhat98 In addition to removing punctuations, we also normalize
numeric expressions when computing CER for benchmark datasets.
Here is Python code (requires [num2words](https://github.com/savoirfairelinux/num2words) library):

```python3
import re
import num2words

text = "4月15日"
conv = lambda m: num2words.num2words(m.group(0), lang='ja')
text = re.sub(r'\d+\.?\d*', conv, text)  # "四月十五日"
```

This logic is in accordance with what the previous researches did (for
example, see [JTubeSpeech](https://github.com/sarulab-speech/Jtubespeech/blob/master/scripts/align.py#L80-L81)), and I think this is likely the reason why
you got a different result.

> Calculating the CER for each utterance and taking the arithmetic mean of all utterances.
> Merging the reference text and predicted text for each utterance and calculating the CER for the entire dataset.

I think the standard way to compute CER for an entire dataset is  $\frac{\sum{\textit{edit distance}}}{\sum{\textit{len(ground truth)}}}$.
See [how Kaldi computes WER](https://github.com/kaldi-asr/kaldi/blob/master/src/bin/compute-wer.cc#L104-L107) for reference.

**Comment by sinhat98** [comment]
Thanks! I will try.

**Comment by sinhat98** [comment]
@fujimotos 
I calculated the `edit_dist` and `gt_len` using code such as following, took the sum of them for all utterances, and calculated the CER, which was **10.9%**. However, the score has not been reproduced yet. What could be the possible reasons for this? Could it be because of different pre-processing of the dataset?

```python
import num2words
from reazonspeech import transcribe, build_sentences
from reazonspeech.text import normalize, _editdist

conv = lambda m: num2words.num2words(m.group(0), lang='ja')
sub_fn = lambda txt: re.sub(r'\d+\.?\d*', conv, txt)

captions = transcribe(audio, speech2text)
caption = build_sentences(captions)[0]
pred = caption.text

text = sub_fn(normalize(text))
pred = sub_fn(normalize(pred))

edit_dist = _editdist(text, pred)
gt_len = len(text)
```

**Comment by fujimotos** [comment]
> captions = transcribe(audio, speech2text)
> caption = build_sentences(captions)[0]

@sinhat98 `build_sentences` is for corpus extraction. This is a helper
function to extract sentences from raw MPEG2-TS packets, so it makes
little sense to use the function here.

Also, `build_sentence(captions)[0]` means that you only consider the first
sentence of the entire subscription text. I suspect that this caused higher
CER score in your evaluation.

Instead of this, you should just concatenate the captions:

```python3
captions = transcribe(audio, speech2text)
pred = "".join([cap for cap in captions])

text = sub_fn(normalize(text))
pred = sub_fn(normalize(pred))

edit_dist = _editdist(text, pred)
gt_len = len(text)
```

**Comment by fujimotos** [comment]
> sub_fn = lambda txt: re.sub(r'\d+\.?\d*', conv, txt)
> ...
> text = sub_fn(normalize(text))

@sinhat98 *Addendum:* Since `normalize()` converts ASCII numerics
to full-width numbers (e.g. `1` to `１`), I guess your `sub_fn` is not actually
working intended here.

* `re.sub(r'\d+\.?\d*', conv, s)` will always find zero match.

Combined with the comment above, please try the following code and
compute the CER:

```python3
PUNCTUATIONS = {ord(x): "" for x in "、。「」『』，,？！!!?!?"}
ZENKAKU = "ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ０>１２３４５６７８９"
HANKAKU = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
ZEN2HAN = str.maketrans(ZENKAKU, HANKAKU)

def normalize(s):
    s = s.translate(PUNCTUATIONS).translate(ZEN2HAN)
    conv = lambda m: num2words.num2words(m.group(0), lang='ja')
    return re.sub(r'\d+\.?\d*', conv, s)

captions = transcribe(audio, speech2text)
pred = "".join([cap.text for cap in captions])

text = normalize(text)
pred = normalize(pred)

edit_dist = _editdist(text, pred)
gt_len = len(text)
```

**Comment by sinhat98** [comment]
When I evaluated it using the method you taught me, I obtained a score of 9.88%.
I think I was able to reproduce it generally, so I will close this issue. Thank you very much!
