### ISSUE TITLE
ASSWriter _format_time Error

### ISSUE THREAD

**Issue by zsz23187** [reazon-research/ReazonSpeech#18]
エラー報告

エラーの内容：
ASSWriterクラスの_format_timeメソッドで、60分以上の時間を処理するときに、分数が正しく表示されない問題が発生しました。例えば、secondsが3601の場合、_format_timeは"1:60:01.00"を返しますが、正しい結果は"1:00:01.00"です。

エラーの原因：
_format_timeメソッドで、分数を計算するときに、時間数の60倍を引かなかったためです。m = int(seconds / 60)という式では、時間数の影響を除外していません。

エラーの解決方法：
_format_timeメソッドで、分数を計算するときに、時間数の60倍を引くように修正しました。m = int(seconds / 60) - h * 60という式に変更しました。

修正後のコード：

    @staticmethod
    def _format_time(seconds):
        h = int(seconds / 3600)
        m = int(seconds / 60) - h * 60 # 時間数の60倍を引く
        s = int(seconds % 60)
        cs = int((seconds % 1) * 100)
        return "%i:%02i:%02i.%02i" % (h, m, s, cs)

**Comment by fujimotos** [comment]
> ASSWriterクラスの_format_timeメソッドで、60分以上の時間を処理するときに、分数が正しく表示されない問題が発生しました。例えば、secondsが3601の場合、_format_timeは"1:60:01.00"を返しますが、正しい結果は"1:00:01.00"です。

@zsz23187 Thank you for reporting. I just pushed a fix for the issue in 30587ad,
so it should be resolved by now. Let me know if anything is not clear.
