### ISSUE TITLE
Charmap encoding error

### ISSUE THREAD

**Issue by fznx922** [reazon-research/ReazonSpeech#21]
Hey there, having issues running the code, seems like its expecting uft8 and getting something else? not sure how to go about fixing it so thought id ask here

hope you can help 

ありがとうございます!

(reazon) h:\reazon>reazonspeech -o z.vtt z.mp3
Fetching 8 files: 100%|██████████████████████████████████████████████████████████████████████████| 8/8 [00:00<?, ?it/s]
Transcribing:   0%|                                                                            | 0/1334 [00:00<?, ?s/s]Traceback (most recent call last):
  File "H:\reazon\reazon\Scripts\reazonspeech-script.py", line 33, in <module>
    sys.exit(load_entry_point('reazonspeech==1.1.0', 'console_scripts', 'reazonspeech')())
  File "H:\reazon\reazon\lib\site-packages\reazonspeech\cli.py", line 229, in main
    writer.caption(outfile, caption)
  File "H:\reazon\reazon\lib\site-packages\reazonspeech\cli.py", line 66, in caption
    file.write("%s --> %s\n%s\n\n" % (start, end, caption.text))
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 31-45: character maps to <undefined>
Transcribing:   0%|                                                                            | 0/1334 [00:09<?, ?s/s]

**Comment by fujimotos** [comment]
@fznx922 Try this and see if it works:

```
% chcp 65001
% reazonspeech z.mp3
```

Your Windows terminal is operating in CP1252 (i.e. latin-1) mode.
Since ReazonSpeech is Japanese ASR model, your console could not
recognize the output properly (hence `UnicodeEncodeError`).

Switching to UTF-8 (= `65001`) should resolve your issue.

**Comment by fujimotos** [comment]
@fznx922 If just running `pip install` does not work, you should start from
setting up CUDA-enabeld ESPnet following the official documentation:

https://espnet.github.io/espnet/installation.html

After that, you can install reazonspeech on top of ESPnet:

```
$ pip install --no-deps git+https://github.com/reazon-research/ReazonSpeech
```

Our repo dose not require any special CUDA modules. All you need is a
working GPU-accerelated ESPnet environment.
