### ISSUE TITLE
Windows 10 + Miniconda3 環境で実行の際に PermissionError が出る。

### ISSUE THREAD

**Issue by masatatsu8** [reazon-research/ReazonSpeech#24]
2.0 に関するエラー報告です。

Windows 10 + Miniconda3 (Python 3.10.13)  環境で, HowToの内容を試したところ、下記のエラーとなりました。

環境変数 TEMP, TMP は C:\temp と設定しています。

```
(reazonspeech) C:\Users\masatatsu\work\reazonspeech>python test.py
Transcribing:   0%|                                                                              | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\tatsumi223057\work\reazonspeech\test.py", line 10, in <module>
    ret = transcribe(model, audio)
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\reazonspeech\nemo\asr\transcribe.py", line 50, in transcribe
    hyp, _ = model.transcribe(
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\nemo\collections\asr\models\rnnt_models.py", line 294, in transcribe
    for test_batch in tqdm(temporary_datalayer, desc="Transcribing", disable=(not verbose)):
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\nemo\collections\asr\data\audio_to_text.py", line 477, in __getitem__
    features = self.featurizer.process(
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\nemo\collections\asr\parts\preprocessing\features.py", line 186, in process
    audio = AudioSegment.from_file(
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\nemo\collections\asr\parts\preprocessing\segment.py", line 259, in from_file
    samples = Audio.from_file(audio_file)
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\pydub\audio_segment.py", line 651, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "C:\ProgramData\miniconda3\envs\reazonspeech\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'c:\\Temp\\tmp4jot4h0y'
```

なお、コードは以下の通りです。 (HowTo から変更していません）

```
from reazonspeech.nemo.asr import load_model, transcribe, audio_from_path

# 実行時にHugging Faceからモデルを取得します (2.3GB)
model = load_model(device='cuda')

# ローカルの音声ファイルを読み込む
audio = audio_from_path('speech-001.wav')

# 音声認識を適用する
ret = transcribe(model, audio)

print(ret.text)
```

**Comment by fangquinlan** [comment]
我也有同样的问题。不过我让GPT4修改了transcribe.py。现在可以运行了。就是不知道这个修改有什么问题...我不懂编程...

`import tempfile
import os
import dataclasses
import torch
from .interface import TranscribeConfig
from .decode import decode_hypothesis, PAD_SECONDS
from .audio import audio_to_file, pad_audio, norm_audio
from nemo.collections.asr.models import EncDecRNNTBPEModel

def load_model(device=None):
    """Load ReazonSpeech model"""
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    from nemo.utils import logging
    logging.setLevel(logging.ERROR)
    return EncDecRNNTBPEModel.from_pretrained('reazon-research/reazonspeech-nemo-v2', map_location=device)

def transcribe(model, audio, config=None):
    """Inference audio data using NeMo model"""
    if config is None:
        config = TranscribeConfig()

    audio = pad_audio(norm_audio(audio), PAD_SECONDS)

    # Use delete=False to keep the file after closing
    with tempfile.NamedTemporaryFile(delete=False) as tmpf:
        audio_to_file(tmpf, audio)
        tmpf_path = tmpf.name  # Store the temp file path to use after closing

    # Make sure to close the file before passing its path to model.transcribe
    try:
        hyp, _ = model.transcribe(
            [tmpf_path],
            batch_size=1,
            return_hypotheses=True,
            verbose=config.verbose
        )
    finally:
        # Ensure the temp file is deleted even if transcribing fails
        os.remove(tmpf_path)

    return decode_hypothesis(model, hyp[0]) if hyp else None

# Ensure the rest of your .py file's content remains unchanged.`

**Comment by fangquinlan** [comment]
我也有同样的问题。不过我让GPT4修改了transcribe.py。现在可以运行了。就是不知道这个修改有什么问题...我不懂编程...

`import tempfile
import os
import dataclasses
import torch
from .interface import TranscribeConfig
from .decode import decode_hypothesis, PAD_SECONDS
from .audio import audio_to_file, pad_audio, norm_audio
from nemo.collections.asr.models import EncDecRNNTBPEModel

def load_model(device=None):
    """Load ReazonSpeech model"""
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    from nemo.utils import logging
    logging.setLevel(logging.ERROR)
    return EncDecRNNTBPEModel.from_pretrained('reazon-research/reazonspeech-nemo-v2', map_location=device)

def transcribe(model, audio, config=None):
    """Inference audio data using NeMo model"""
    if config is None:
        config = TranscribeConfig()

    audio = pad_audio(norm_audio(audio), PAD_SECONDS)

    # Use delete=False to keep the file after closing
    with tempfile.NamedTemporaryFile(delete=False) as tmpf:
        audio_to_file(tmpf, audio)
        tmpf_path = tmpf.name  # Store the temp file path to use after closing

    # Make sure to close the file before passing its path to model.transcribe
    try:
        hyp, _ = model.transcribe(
            [tmpf_path],
            batch_size=1,
            return_hypotheses=True,
            verbose=config.verbose
        )
    finally:
        # Ensure the temp file is deleted even if transcribing fails
        os.remove(tmpf_path)

    return decode_hypothesis(model, hyp[0]) if hyp else None`

**Comment by fangquinlan** [comment]
import tempfile
import os
import dataclasses
import torch
from .interface import TranscribeConfig
from .decode import decode_hypothesis, PAD_SECONDS
from .audio import audio_to_file, pad_audio, norm_audio
from nemo.collections.asr.models import EncDecRNNTBPEModel

def load_model(device=None):
    """Load ReazonSpeech model"""
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    from nemo.utils import logging
    logging.setLevel(logging.ERROR)
    return EncDecRNNTBPEModel.from_pretrained('reazon-research/reazonspeech-nemo-v2', map_location=device)

def transcribe(model, audio, config=None):
    """Inference audio data using NeMo model"""
    if config is None:
        config = TranscribeConfig()

    audio = pad_audio(norm_audio(audio), PAD_SECONDS)

    # Use delete=False to keep the file after closing
    with tempfile.NamedTemporaryFile(delete=False) as tmpf:
        audio_to_file(tmpf, audio)
        tmpf_path = tmpf.name  # Store the temp file path to use after closing

    # Make sure to close the file before passing its path to model.transcribe
    try:
        hyp, _ = model.transcribe(
            [tmpf_path],
            batch_size=1,
            return_hypotheses=True,
            verbose=config.verbose
        )
    finally:
        # Ensure the temp file is deleted even if transcribing fails
        os.remove(tmpf_path)

    return decode_hypothesis(model, hyp[0]) if hyp else None

# Ensure the rest of your .py file's content remains unchanged.


GPT4帮我修改了transcribe文件，现在似乎可以运行了。不过我不知道有没有什么问题....

**Comment by fangquinlan** [comment]
`
import tempfile
import os
import dataclasses
import torch
from .interface import TranscribeConfig
from .decode import decode_hypothesis, PAD_SECONDS
from .audio import audio_to_file, pad_audio, norm_audio
from nemo.collections.asr.models import EncDecRNNTBPEModel

def load_model(device=None):
    """Load ReazonSpeech model"""
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    from nemo.utils import logging
    logging.setLevel(logging.ERROR)
    return EncDecRNNTBPEModel.from_pretrained('reazon-research/reazonspeech-nemo-v2', map_location=device)

def transcribe(model, audio, config=None):
    """Inference audio data using NeMo model"""
    if config is None:
        config = TranscribeConfig()

    audio = pad_audio(norm_audio(audio), PAD_SECONDS)

    # Use delete=False to keep the file after closing
    with tempfile.NamedTemporaryFile(delete=False) as tmpf:
        audio_to_file(tmpf, audio)
        tmpf_path = tmpf.name  # Store the temp file path to use after closing

    # Make sure to close the file before passing its path to model.transcribe
    try:
        hyp, _ = model.transcribe(
            [tmpf_path],
            batch_size=1,
            return_hypotheses=True,
            verbose=config.verbose
        )
    finally:
        # Ensure the temp file is deleted even if transcribing fails
        os.remove(tmpf_path)

    return decode_hypothesis(model, hyp[0]) if hyp else None
`

GPT4帮我修改了transcribe文件，现在似乎可以运行了.不过我不知道有什么用什么问题....

**Comment by fangquinlan** [comment]
```python
import tempfile
import os
import dataclasses
import torch
from .interface import TranscribeConfig
from .decode import decode_hypothesis, PAD_SECONDS
from .audio import audio_to_file, pad_audio, norm_audio
from nemo.collections.asr.models import EncDecRNNTBPEModel

def load_model(device=None):
    """Load ReazonSpeech model"""
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    from nemo.utils import logging
    logging.setLevel(logging.ERROR)
    return EncDecRNNTBPEModel.from_pretrained('reazon-research/reazonspeech-nemo-v2', map_location=device)

def transcribe(model, audio, config=None):
    """Inference audio data using NeMo model"""
    if config is None:
        config = TranscribeConfig()

    audio = pad_audio(norm_audio(audio), PAD_SECONDS)

    # Use delete=False to keep the file after closing
    with tempfile.NamedTemporaryFile(delete=False) as tmpf:
        audio_to_file(tmpf, audio)
        tmpf_path = tmpf.name  # Store the temp file path to use after closing

    # Make sure to close the file before passing its path to model.transcribe
    try:
        hyp, _ = model.transcribe(
            [tmpf_path],
            batch_size=1,
            return_hypotheses=True,
            verbose=config.verbose
        )
    finally:
        # Ensure the temp file is deleted even if transcribing fails
        os.remove(tmpf_path)

    return decode_hypothesis(model, hyp[0]) if hyp else None

# Ensure the rest of your .py file's content remains unchanged.
```

GPT4帮我修改了transcribe文件，现在似乎可以运行了.不过我不知道有什么用什么问题....

**Comment by fangquinlan** [comment]
```python
import tempfile
import os
import dataclasses
import torch
from .interface import TranscribeConfig
from .decode import decode_hypothesis, PAD_SECONDS
from .audio import audio_to_file, pad_audio, norm_audio
from nemo.collections.asr.models import EncDecRNNTBPEModel

def load_model(device=None):
    """Load ReazonSpeech model"""
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    from nemo.utils import logging
    logging.setLevel(logging.ERROR)
    return EncDecRNNTBPEModel.from_pretrained('reazon-research/reazonspeech-nemo-v2', map_location=device)

def transcribe(model, audio, config=None):
    """Inference audio data using NeMo model"""
    if config is None:
        config = TranscribeConfig()

    audio = pad_audio(norm_audio(audio), PAD_SECONDS)

    # Use delete=False to keep the file after closing
    with tempfile.NamedTemporaryFile(delete=False) as tmpf:
        audio_to_file(tmpf, audio)
        tmpf_path = tmpf.name  # Store the temp file path to use after closing

    # Make sure to close the file before passing its path to model.transcribe
    try:
        hyp, _ = model.transcribe(
            [tmpf_path],
            batch_size=1,
            return_hypotheses=True,
            verbose=config.verbose
        )
    finally:
        # Ensure the temp file is deleted even if transcribing fails
        os.remove(tmpf_path)

    return decode_hypothesis(model, hyp[0]) if hyp else None

# Ensure the rest of your .py file's content remains unchanged.
```

GPT4帮我修改了transcribe.py文件。现在似乎可以运行了。不过我不知道有没有问题：

```python
(base) PS C:\Users\X\Desktop\voice> reazonspeech-nemo-asr 1.mp3
[NeMo W 2024-02-16 15:39:18 nemo_logging:393] Could not import NeMo NLP collection which is required for speech translation model.
Beam search progress:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.56s/sample]
Transcribing: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:20<00:00, 20.19s/it]
[00:00:00.000 --> 00:00:02.700] ニャン草はあかわないでいただけますかキュウガさん
[00:00:03.419 --> 00:00:05.900] とペの低い方の難所が言った
[00:00:06.940 --> 00:00:11.419] 牛賀はデスクを挟んで向かい合っているアンヒエの顔をしばし眺め
[00:00:12.060 --> 00:00:15.179] それから自分のシミに挟まれたセブンスターに目をやった
[00:00:16.219 --> 00:00:19.179] 男装には火はついていない申し訳ありません
[00:00:19.740 --> 00:00:22.780] が尊子はあくまで生き理的に言い添えた
[00:00:23.420 --> 00:00:25.980] そんなものをどうして自分が手にしているんだろうという
[00:00:26.940 --> 00:00:32.140] 怒った表情を旧側は浮かべたああこれはどうもいけませんね
[00:00:32.859 --> 00:00:38.300] もちろん歩なんかつけません自分でも知らないうちに党が勝手に驚いてしまうんです
[00:00:39.259 --> 00:00:43.899] のこは悪億センチほど情が刺したが実現はみじんもやぐらがなかった
[00:00:44.539 --> 00:00:47.579] その経典は牛和の目に酷定されたままだ
[00:00:48.300 --> 00:00:52.219] 友愛はイエンサーを和尚に戻し中道を引き出しにしまった
```

**Comment by fujimotos** [comment]
@masatatsu8 ご報告、ありがとうございます。
先ほど、 ee81069a6b6 でnemo-asrにWindowsサポートを追加しました。

* Windows Sever 2022 + Python 3.11.8 で動作を確認しています。
* この最新版だと、ご指摘のエラーが解消されているはずです。

取り急ぎ共有まで。

**Comment by fujimotos** [comment]
@fangquinlan I pushed ee81069 that should resolve the issue.

I could confirm that the latest master branch now works on Windows Server 2022.
Let me know if it does not work.
