### ISSUE TITLE
dataset download error

### ISSUE THREAD

**Issue by hotbaby** [reazon-research/ReazonSpeech#28]
ReazonSpeech download error.

```
Request forbidden by administrative rules.
```

**Comment by sin2piusc** [comment]
Max retries exceeded with url: /v2-tsv/small.tsv (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)

**Comment by fujimotos** [comment]
ReazonSpeech dataset is up again now.
