### ISSUE TITLE
Failed to download the "all" size

### ISSUE THREAD

**Issue by zszheng147** [reazon-research/ReazonSpeech#29]
`load_dataset` from `huggingface` is extremely slow and I have been stuck for days (almost a week).

**Comment by fujimotos** [comment]
Set up a server located in Japan (prefereably somewhere near Tokyo), and try
downloading the dataset from there.

ReazonSpeech is hosted on [ABCI cloud.](https://abci.ai/) It's slow to download
if you are using an overseas connection.

**Comment by zszheng147** [comment]
Thank you for your quick response. The issue is not related to network problems. I have already downloaded the intermediate data, which is stored in the downloads folder within my cache folder. I assume that the Huggingface API is supposed to unpack or process these intermediate tar files, but this is where I'm encountering difficulties, and it has been quite time-consuming.
