### ISSUE TITLE
About HANKAKU and ZENKAKU substitution

### ISSUE THREAD

**Issue by sejimak** [reazon-research/ReazonSpeech#3]
Thank you very much for your great work.
After reviewing the source code below, I thought there was a concise way to write it in the HANKAKU to ZENKAKU conversion section.
`ReazonSpeech/reazonspeech/text.py`

You define it as follows
``` python 
_HAN2ZEN = str.maketrans(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    "ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ０１２３４５６７８９")

...
return text.translate(_SPECIALS).translate(_HAN2ZEN)
```

However, since `espnet` is required to use this tool, the dependent library `jaconv` should be installed.
Therefore, it is believed that this code can be realized with the following

``` python
return jaconv.h2z(text, kana=True, digit=True, ascii=True)
```
I hope this is helpful.

**Comment by fujimotos** [comment]
Thank you for your suggestion!

> After reviewing the source code below, I thought there was a concise way to write it in the HANKAKU to ZENKAKU conversion section.

Yes, normalization is definitely one of the areas where ReazonSpeech can improve.

We hand-crafted a vary basic normalization rule for the initial version. However,
we are considering to revisit & expand the normalization rules.

* There are several options to consider, including `jaconv` as you mentioned.

We'll take your suggestion into the consideration. So thank you again for your
feedback!
