### ISSUE TITLE
Do you have plans to open source reazonspeech-zipformer-large model? 

### ISSUE THREAD

**Issue by jiangzhuo** [reazon-research/ReazonSpeech#32]
I noticed this [commit](https://github.com/reazon-research/ReazonSpeech/commit/fac1f39ae9468793ad6fca319f6ddbf3c6c8482c).
It sounds like a zipformer model trained on the reazonspeech corpus? It will be very useful.

**Comment by fujimotos** [comment]
> It sounds like a zipformer model trained on the reazonspeech corpus? 

@jiangzhuo Right, we are currently preparing a release. I think we can
release `v2.1` this week or so.

I'll let you know once we have done the release. WFM.

**Comment by fujimotos** [comment]
ReazonSpeech v2.1 is now public. Check out the following blog post for details:

https://research.reazon.jp/blog/2024-08-01-ReazonSpeech.html

Looking forward to feedback from you guys!

**Comment by fujimotos** [comment]
ReazonSpeech v2.1 is now public. Check out the following blog post for more details:

https://research.reazon.jp/blog/2024-08-01-ReazonSpeech.html

**Comment by csukuangfj** [comment]
FYI: We have added it to sherpa-onnx.

Please see
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-transducer/zipformer-transducer-models.html#sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01-japanese

![Screenshot 2024-08-01 at 21 28 22](https://github.com/user-attachments/assets/1ef731c9-06a9-41cd-9253-21d539c4bec7)

---

We have also made an Android demo for it with silero-vad, which can be found at
https://www.bilibili.com/video/BV1BRvve1ESV

You can find the APK at
https://k2-fsa.github.io/sherpa/onnx/vad/apk-asr.html

e.g.,
https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/vad-asr/1.10.20/sherpa-onnx-1.10.20-arm64-v8a-vad_asr-ja-zipformer_reazonspeech.apk

---

Hope that a streaming model would be available soon

**Comment by jiangzhuo** [comment]
Thank you for your work, looking forward to future progress, such as streaming ASR capabilities.

**Comment by fujimotos** [comment]
> FYI: We have added it to sherpa-onnx.
> ...
> We have also made an Android demo for it with silero-vad, which can be found at

@csukuangfj I just shared your post with our team, and they were both
throughly impressed and thrilled by your demo. Thank you!
