### ISSUE TITLE
Downloading the dataset from Hugging Face was unsuccessful.

### ISSUE THREAD

**Issue by JiabinXue** [reazon-research/ReazonSpeech#34]
I'm very grateful for your open-source dataset. I attempted to download this dataset from Hugging Face, but encountered network issues that prevented the download.

ConnectionError: Couldn't reach https://reazonspeech.s3.abci.ai/v2-tsv/all.tsv (ProxyError(MaxRetryError("HTTPSConnectionPool(host='reazonspeech.s3.abci.ai', port=443): Max retries exceeded with url: /v2-tsv/all.tsv (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 504 Gateway Time-out')))))

**Comment by fujimotos** [comment]
> encountered network issues that prevented the download.

@JiabinXue We use ABCI, a regional cloud service run by AIST, for hosting ReazonSpeech corpus.

Right now ABCI is under scheduled maintenance. For this reason, our corpus cannot be accessed
from internet. You can view the maintenance schedule on AIST's website:

* https://abci.ai/en/about_abci/info.html

So wait for further updates from AIST. Once the maintenance is done, our corpus will be available again.

**Comment by JiabinXue** [comment]
> > encountered network issues that prevented the download.
> 
> @JiabinXue We use ABCI, a regional cloud service run by AIST, for hosting ReazonSpeech corpus.
> 
> Right now ABCI is under scheduled maintenance. For this reason, our corpus cannot be accessed from internet. You can view the maintenance schedule on AIST's website:
> 
> * https://abci.ai/en/about_abci/info.html
> 
> So wait for further updates from AIST. Once the maintenance is done, our corpus will be available again.

Thank you for your response. I will try again after the maintenance is finished.
