### ISSUE TITLE
downloading the dataset connection timeout

### ISSUE THREAD

**Issue by verbose-void** [reazon-research/ReazonSpeech#35]
when trying to download the reazonspeech dataset on huggingface, i was getting ConnectionTimeout. after [following the link](https://reazonspeech.s3.abci.ai/v2-tsv/small.tsv)- the webpage results in a loading error like this:

![image](https://github.com/user-attachments/assets/76c923a8-9219-486e-b50c-22c9abb0b0bf)

**Comment by fujimotos** [comment]
See #34. The hosting service is currently under maintenance, so
you need to wait a bit until the service becomes online again.
