### ISSUE TITLE
ReazonSpeech v1.1モデルのリリース

### ISSUE THREAD

**Issue by fujimotos** [reazon-research/ReazonSpeech#7]
### ゴール

* 2023年春頃を目標に`reazonspeech-espnet-v1.1` をリリースする。
* 音声認識の精度・ロバストネスを向上させ、さらに長時間音声の文字起こしに対応する。

### v1からの改善点

1. ノイズに対するロバストネスを向上させる #4
2. 複数の発話が含まれる音声に対応する #5
3. 長時間音声の文字起こしをサポートする #6

### 備考

* それぞれの改善はGitHub Issueを利用して、公開の場で進める。
* ESPnetプロジェクトに還元可能な点は可能な限りフィードバックする。

**Comment by fujimotos** [comment]
NLP2023の会期中に並行して回していた実験の結果が出たので共有します。

* 今回、ReazonSpeech v1 (15kh) でデータ量は約1.5倍に拡大しています。
* 重要なポイントとして、データ拡張をアグレッシブに適用し、75%にAugmentを施しました。
* さらに、今回からWhisperと同じように、推論前に入力音声のパディングを行うようにしています。

**実験サマリー**

| 項目 | 内容 |
| ------------ | ----------------------------- |
| 学習データ   | ReazonSpeechコーパス・22218時間 |
| モデル       | ESPnet Conformer モデル       |   
| パラメータ数 | 約90M                         |   
| データ拡張   | MUSAN + カットオフ を37.5%ずつに適用 |

**主な結果**  

以下の数字は実験のPreliminaryな結果値です。まだ研究は進行中のステータスのため、正確な数値は追って発表します。

![inhouse](https://user-images.githubusercontent.com/8974561/225776394-81df3e38-84b5-4d83-9300-92c3afa7ea10.png)

**Comment by fujimotos** [comment]
@sw005320 JFYI, I wrote [a short review](https://github.com/reazon-research/ReazonSpeech/issues/7#issuecomment-1502577390) of enhancements we made to train a
better ESPnet Japanese ASR model (which we released as `ReazonSpeech v1.1`
last week).

* Release Note: https://github.com/reazon-research/ReazonSpeech/releases/tag/v1.1.0
* Hugging Face: https://huggingface.co/reazon-research/reazonspeech-espnet-next
* Blog: https://research.reazon.jp/blog/2023-04-04-ReazonSpeech.html

We sincerely thank you for all the suggestions you gave us! They were super
helpful!

**Comment by sw005320** [comment]
Very cool!
Can you make a PR to https://github.com/espnet/espnet/tree/master/egs2/reazonspeech/asr1 about this new training scheme?
We have discussed that the result through our discussions should be open-sourced.

**Comment by fujimotos** [comment]
> Can you make a PR to https://github.com/espnet/espnet/tree/master/egs2/reazonspeech/asr1 about this new training scheme?

@sw005320 We are currently working on it!

We're planning to upstream the imrpvoments as a series of
PRs, so just wait for us a bit.

**Comment by fujimotos** [comment]
Now we can close this ticket as resolved.
